# Generated by Django 3.2.9 on 2021-11-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='option_three',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
