# Generated by Django 3.2.9 on 2021-11-02 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_poll_option_three'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='option_three',
        ),
    ]
