# Generated by Django 3.2.9 on 2021-11-03 23:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_remove_poll_option_three'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='poll_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
