# Generated by Django 3.2.9 on 2021-11-04 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_poll_poll_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='poll_id',
        ),
    ]
